language: generic
dist: trusty
sudo: required
cache: apt
services: docker
matrix:
  fast_finish: true

env:
  global:
  - DEBIAN_FRONTEND=noninteractive
  - ROS_DISTRO=kinetic
  - QT_X11_NO_MITSHM=1
  - DISPLAY=:0
  - DOCKER_IMAGE="osrf/ros:$ROS_DISTRO-desktop"
  - BUILD_PKGS="jsk_darwin"
  matrix:
  - TEST_PKGS="jsk_darwin"
before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
before_script:
  - sudo apt-get update -q || echo Ignore error of apt-get update
  - sudo -E apt-get -y -q -qq install mesa-utils xserver-xorg-video-dummy xvfb x11-xserver-utils x11-xfs-utils
  - sudo -E Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile /tmp/xorg.log -config $CI_SOURCE_PATH/.ci/dummy.xorg.conf $DISPLAY &
  - sleep 1
  - glxinfo | grep GLX || cat /tmp/xorg.log
  - xhost +local:root
script:
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - docker run -i -v $CI_SOURCE_PATH:$CI_SOURCE_PATH -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME:$HOME -e QT_X11_NO_MITSHM -e DISPLAY -e CI_SOURCE_PATH -e HOME -e ROS_DISTRO -e BUILD_PKGS -e TEST_PKGS -e CMAKE_ARGS -e REPOSITORY_NAME -e DEBIAN_FRONTEND -t "$DOCKER_IMAGE" sh -c "cd $CI_SOURCE_PATH; ./.ci/docker.sh"
after_success:
  - sudo chown -R travis:travis /home/travis
